/* ============================================================
   The Urlcade — example cart: Breakout

   Not authored in this repo — vendored from a fragment built entirely
   by an external agent working purely against the cart-authoring skill
   and the live site, with no access to this codebase at all (DESIGN.md
   §35).
   It shipped on the shelf as a bare externally-registered fragment
   first; when the cart binary format broke (formatVersion 2, DESIGN.md
   §36 — a new hook, a new header field), that fragment stopped
   decoding under the new kernel. Rather than lose it, this file is its
   disassembly (kernel.js's formatDisassembly(), run against the
   original formatVersion:1 bytes before the format changed), captured
   as real, re-assemblable source and recompiled fresh — a
   decompile-then-recompile round trip is always valid (bytecode back to
   mnemonics back to identical bytecode), used here to carry a cart
   across a breaking format change instead of to inspect one. No named
   constants/globals — a
   decompile never has them (assemble()'s constants/globals maps only
   exist in hand-authored source, never in the binary itself); every
   operand below is just the numeric index formatDisassembly resolved it to.
   ============================================================ */
"use strict";

function buildBreakoutCart(){
  const cart = {
    formatVersion: 3,
    name: "Breakout", author: "Claude", // vendored, not authored here — see header comment
    cartType: 1,
    // Terrain hue 220 (dark blue background/bricks). Entity hue hint ~32
    // (orange) for the paddle/ball — DESIGN.md §44.
    paletteParams: [220,0,15,70,8,55,23,107],
    rngSeed: 1,
    modeFlags: 0,
    screenW: 160, screenH: 160,
    backdropFillIndex: 0, backdropGroundHeight: 0, backdropGroundIndex: 0,
    inputActiveButtons: 3,
    inputTouchTemplate: 2,
    inputButtonLabels: {"1":"Left","2":"Right"},
    hudSpec: [
      {
        "kind": 0,
        "sourceKind": 0,
        "srcA": 2,
        "srcB": 0,
        "delta": 0,
        "suffixConstIdx": 255,
        "clamp": 0,
        "label": "Score"
      },
      {
        "kind": 1,
        "sourceKind": 0,
        "srcA": 4,
        "srcB": 0,
        "delta": 0,
        "suffixConstIdx": 255,
        "clamp": 0,
        "label": "Game Over - refresh to retry"
      },
      {
        "kind": 1,
        "sourceKind": 0,
        "srcA": 5,
        "srcB": 0,
        "delta": 0,
        "suffixConstIdx": 255,
        "clamp": 0,
        "label": "You Win! - refresh to play again"
      }
    ],
    constants: [3,148,16,4,80,130,1.600000023841858,-2.4000000953674316,4,160,160,5,8,10,20,20,12,0.11999999731779099],
    entityTypes: [
      {
        "renderKind": 0,
        "assetIndex": 0,
        "rotateFlag": 0,
        "collisionW": 32,
        "collisionH": 8,
        "extFieldCount": 0
      },
      {
        "renderKind": 0,
        "assetIndex": 1,
        "rotateFlag": 0,
        "collisionW": 8,
        "collisionH": 8,
        "extFieldCount": 0
      },
      {
        "renderKind": 0,
        "assetIndex": 2,
        "rotateFlag": 0,
        "collisionW": 18,
        "collisionH": 8,
        "extFieldCount": 0
      }
    ],
    sprites: [
      {
        "kind": 1,
        "w": 32,
        "h": 8,
        "shapes": [
          {
            "type": 1,
            "x": 0,
            "y": 0,
            "w": 0,
            "h": 8,
            "color": 10
          },
          {
            "type": 1,
            "x": 2,
            "y": 2,
            "w": 28,
            "h": 2,
            "color": 11
          }
        ]
      },
      {
        "kind": 1,
        "w": 8,
        "h": 8,
        "shapes": [
          {
            "type": 0,
            "cx": 4,
            "cy": 4,
            "rx": 3.625,
            "ry": 3.625,
            "color": 11
          }
        ]
      },
      {
        "kind": 1,
        "w": 18,
        "h": 8,
        "shapes": [
          {
            "type": 1,
            "x": 0,
            "y": 0,
            "w": 18,
            "h": 8,
            "color": 6
          },
          {
            "type": 1,
            "x": 1,
            "y": 1,
            "w": 16,
            "h": 6,
            "color": 4
          }
        ]
      }
    ],
    tiles: [],
    mapGenerator: 0,
  hooks: {
    on_init: [
      "B0:",
      "    SPAWN 0",
      "    STOREG 0",
      "    PUSHC 9",
      "    PUSHI 2",
      "    DIV",
      "    STOREE 0 0",
      "    PUSHC 1",
      "    STOREE 0 1",
      "    SPAWN 1",
      "    STOREG 1",
      "    PUSHC 4",
      "    STOREE 1 0",
      "    PUSHC 5",
      "    STOREE 1 1",
      "    PUSHC 6",
      "    STOREE 1 2",
      "    PUSHC 7",
      "    STOREE 1 3",
      "    PUSHI 0",
      "    STOREG 2",
      "    PUSHI 0",
      "    STOREG 3",
      "    PUSHI 0",
      "    STOREG 4",
      "    PUSHI 0",
      "    STOREG 5",
      "    PUSHI 0",
      "    STOREG 6",
      "B1:",
      "    LOADG 6",
      "    PUSHC 11",
      "    CMPGE",
      "    JNZ B6",
      "B2:",
      "    PUSHI 0",
      "    STOREG 7",
      "B3:",
      "    LOADG 7",
      "    PUSHC 12",
      "    CMPGE",
      "    JNZ B5",
      "B4:",
      "    LOADG 7",
      "    PUSHC 15",
      "    MUL",
      "    PUSHC 13",
      "    ADD",
      "    STOREG 8",
      "    LOADG 6",
      "    PUSHC 16",
      "    MUL",
      "    PUSHC 14",
      "    ADD",
      "    STOREG 9",
      "    SPAWN 2",
      "    STOREG 10",
      "    LOADG 8",
      "    STOREE 10 0",
      "    LOADG 9",
      "    STOREE 10 1",
      "    PUSHI 1",
      "    STOREE 10 5",
      "    LOADG 3",
      "    PUSHI 1",
      "    ADD",
      "    STOREG 3",
      "    LOADG 7",
      "    PUSHI 1",
      "    ADD",
      "    STOREG 7",
      "    JMP B3",
      "B5:",
      "    LOADG 6",
      "    PUSHI 1",
      "    ADD",
      "    STOREG 6",
      "    JMP B1",
      "B6:",
      "    HALT",
    ],
    on_frame: [
      "B0:",
      "    LOADG 4",
      "    JNZ B10",
      "B1:",
      "    LOADG 5",
      "    JNZ B10",
      "B2:",
      "    LOADE 1 0",
      "    LOADE 1 2",
      "    ADD",
      "    STOREE 1 0",
      "    LOADE 1 1",
      "    LOADE 1 3",
      "    ADD",
      "    STOREE 1 1",
      "    LOADE 1 0",
      "    PUSHC 8",
      "    CMPLT",
      "    JZ B4",
      "B3:",
      "    PUSHC 8",
      "    STOREE 1 0",
      "    LOADE 1 2",
      "    NEG",
      "    STOREE 1 2",
      "B4:",
      "    LOADE 1 0",
      "    PUSHC 9",
      "    PUSHC 8",
      "    SUB",
      "    CMPGT",
      "    JZ B6",
      "B5:",
      "    PUSHC 9",
      "    PUSHC 8",
      "    SUB",
      "    STOREE 1 0",
      "    LOADE 1 2",
      "    NEG",
      "    STOREE 1 2",
      "B6:",
      "    LOADE 1 1",
      "    PUSHC 8",
      "    CMPLT",
      "    JZ B8",
      "B7:",
      "    PUSHC 8",
      "    STOREE 1 1",
      "    LOADE 1 3",
      "    NEG",
      "    STOREE 1 3",
      "B8:",
      "    LOADE 1 1",
      "    PUSHC 10",
      "    CMPGT",
      "    JZ B10",
      "B9:",
      "    PUSHI 1",
      "    STOREG 4",
      "B10:",
      "    HALT",
    ],
    on_tick: [
      "B0:",
      "    LOAD_SELF 4",
      "    PUSHI 2",
      "    CMPEQ",
      "    JZ B4",
      "B1:",
      "    LOAD_SELF 5",
      "    PUSHI 0",
      "    CMPGT",
      "    JNZ B4",
      "B2:",
      "    KILL_SELF",
      "    LOADG 2",
      "    PUSHI 10",
      "    ADD",
      "    STOREG 2",
      "    LOADG 3",
      "    PUSHI 1",
      "    SUB",
      "    DUP",
      "    STOREG 3",
      "    JNZ B4",
      "B3:",
      "    PUSHI 1",
      "    STOREG 5",
      "B4:",
      "    HALT",
    ],
    on_input: [
      "B0:",
      "    LOADG 4",
      "    JNZ B10",
      "B1:",
      "    LOADG 5",
      "    JNZ B10",
      "B2:",
      "    LOAD_INPUT",
      "    TESTBIT 0",
      "    JZ B4",
      "B3:",
      "    LOADE 0 0",
      "    PUSHC 0",
      "    SUB",
      "    STOREE 0 0",
      "B4:",
      "    LOAD_INPUT",
      "    TESTBIT 1",
      "    JZ B6",
      "B5:",
      "    LOADE 0 0",
      "    PUSHC 0",
      "    ADD",
      "    STOREE 0 0",
      "B6:",
      "    LOADE 0 0",
      "    PUSHC 2",
      "    CMPLT",
      "    JZ B8",
      "B7:",
      "    PUSHC 2",
      "    STOREE 0 0",
      "    JMP B10",
      "B8:",
      "    LOADE 0 0",
      "    PUSHC 9",
      "    PUSHC 2",
      "    SUB",
      "    CMPGT",
      "    JZ B10",
      "B9:",
      "    PUSHC 9",
      "    PUSHC 2",
      "    SUB",
      "    STOREE 0 0",
      "B10:",
      "    HALT",
    ],
    on_collide: [
      "B0:",
      "    LOAD_A 4",
      "    PUSHI 0",
      "    CMPEQ",
      "    LOAD_B 4",
      "    PUSHI 1",
      "    CMPEQ",
      "    AND",
      "    JZ B3",
      "B1:",
      "    LOAD_B 3",
      "    PUSHI 0",
      "    CMPGT",
      "    JZ B6",
      "B2:",
      "    LOAD_B 3",
      "    NEG",
      "    STORE_B 3",
      "    LOAD_B 0",
      "    LOAD_A 0",
      "    SUB",
      "    PUSHC 17",
      "    MUL",
      "    STORE_B 2",
      "    LOAD_A 1",
      "    PUSHC 3",
      "    SUB",
      "    PUSHC 8",
      "    SUB",
      "    STORE_B 1",
      "    JMP B6",
      "B3:",
      "    LOAD_A 4",
      "    PUSHI 1",
      "    CMPEQ",
      "    LOAD_B 4",
      "    PUSHI 2",
      "    CMPEQ",
      "    AND",
      "    JZ B6",
      "B4:",
      "    LOAD_B 5",
      "    PUSHI 0",
      "    CMPGT",
      "    JZ B6",
      "B5:",
      "    PUSHI 0",
      "    STORE_B 5",
      "    LOAD_A 3",
      "    NEG",
      "    STORE_A 3",
      "B6:",
      "    HALT",
    ],
  },
  };
  return cart;
}

export { buildBreakoutCart };
